import { FlightAirport } from '../types';

/**
 * Curated airport directory.
 *
 * These entries are hand-maintained canonical IATA records. They are never
 * generated by the AI model: an invented IATA code sends a traveller to the
 * wrong airport, so only verified entries belong here. Add new rows by hand.
 *
 * MVP scope, accepted by the Founder on 2026-09-14 with a follow-up to replace
 * this list with a comprehensive canonical airport dataset or provider API.
 * `FlightAirport` is the contract that replacement must keep, so the setup
 * service and the autocomplete UI stay unchanged. The no-AI-IATA rule above
 * carries over to that replacement without exception.
 */
export const AIRPORT_DIRECTORY: FlightAirport[] = [
  { iataCode: 'YYZ', name: 'Toronto Pearson International Airport', city: 'Toronto', country: 'Canada', latitude: 43.6777, longitude: -79.6248 },
  { iataCode: 'YTZ', name: 'Billy Bishop Toronto City Airport', city: 'Toronto', country: 'Canada', latitude: 43.6275, longitude: -79.3962 },
  { iataCode: 'YVR', name: 'Vancouver International Airport', city: 'Vancouver', country: 'Canada', latitude: 49.1967, longitude: -123.1815 },
  { iataCode: 'YUL', name: 'Montréal–Trudeau International Airport', city: 'Montreal', country: 'Canada', latitude: 45.4706, longitude: -73.7408 },
  { iataCode: 'PUS', name: 'Gimhae International Airport', city: 'Busan', country: 'South Korea', latitude: 35.1795, longitude: 128.9382 },
  { iataCode: 'ICN', name: 'Incheon International Airport', city: 'Seoul', country: 'South Korea', latitude: 37.4602, longitude: 126.4407 },
  { iataCode: 'GMP', name: 'Gimpo International Airport', city: 'Seoul', country: 'South Korea', latitude: 37.5583, longitude: 126.7906 },
  { iataCode: 'CJU', name: 'Jeju International Airport', city: 'Jeju', country: 'South Korea', latitude: 33.5113, longitude: 126.4930 },
  { iataCode: 'TPE', name: 'Taiwan Taoyuan International Airport', city: 'Taipei', country: 'Taiwan', latitude: 25.0777, longitude: 121.2328 },
  { iataCode: 'TSA', name: 'Taipei Songshan Airport', city: 'Taipei', country: 'Taiwan', latitude: 25.0694, longitude: 121.5521 },
  { iataCode: 'KHH', name: 'Kaohsiung International Airport', city: 'Kaohsiung', country: 'Taiwan', latitude: 22.5771, longitude: 120.3500 },
  { iataCode: 'NRT', name: 'Narita International Airport', city: 'Tokyo', country: 'Japan', latitude: 35.7720, longitude: 140.3929 },
  { iataCode: 'HND', name: 'Tokyo Haneda Airport', city: 'Tokyo', country: 'Japan', latitude: 35.5494, longitude: 139.7798 },
  { iataCode: 'KIX', name: 'Kansai International Airport', city: 'Osaka', country: 'Japan', latitude: 34.4347, longitude: 135.2441 },
  { iataCode: 'ITM', name: 'Osaka International Airport', city: 'Osaka', country: 'Japan', latitude: 34.7855, longitude: 135.4382 },
  { iataCode: 'CTS', name: 'New Chitose Airport', city: 'Sapporo', country: 'Japan', latitude: 42.7752, longitude: 141.6923 },
  { iataCode: 'FUK', name: 'Fukuoka Airport', city: 'Fukuoka', country: 'Japan', latitude: 33.5859, longitude: 130.4500 },
  { iataCode: 'HKG', name: 'Hong Kong International Airport', city: 'Hong Kong', country: 'Hong Kong', latitude: 22.3080, longitude: 113.9185 },
  { iataCode: 'SIN', name: 'Singapore Changi Airport', city: 'Singapore', country: 'Singapore', latitude: 1.3644, longitude: 103.9915 },
  { iataCode: 'BKK', name: 'Suvarnabhumi Airport', city: 'Bangkok', country: 'Thailand', latitude: 13.6900, longitude: 100.7501 },
  { iataCode: 'DMK', name: 'Don Mueang International Airport', city: 'Bangkok', country: 'Thailand', latitude: 13.9126, longitude: 100.6068 },
  { iataCode: 'PVG', name: 'Shanghai Pudong International Airport', city: 'Shanghai', country: 'China', latitude: 31.1443, longitude: 121.8083 },
  { iataCode: 'SHA', name: 'Shanghai Hongqiao International Airport', city: 'Shanghai', country: 'China', latitude: 31.1979, longitude: 121.3363 },
  { iataCode: 'PEK', name: 'Beijing Capital International Airport', city: 'Beijing', country: 'China', latitude: 40.0799, longitude: 116.6031 },
  { iataCode: 'PKX', name: 'Beijing Daxing International Airport', city: 'Beijing', country: 'China', latitude: 39.5098, longitude: 116.4106 },
  { iataCode: 'LAX', name: 'Los Angeles International Airport', city: 'Los Angeles', country: 'United States', latitude: 33.9416, longitude: -118.4085 },
  { iataCode: 'SFO', name: 'San Francisco International Airport', city: 'San Francisco', country: 'United States', latitude: 37.6213, longitude: -122.3790 },
  { iataCode: 'JFK', name: 'John F. Kennedy International Airport', city: 'New York', country: 'United States', latitude: 40.6413, longitude: -73.7781 },
  { iataCode: 'EWR', name: 'Newark Liberty International Airport', city: 'New York', country: 'United States', latitude: 40.6895, longitude: -74.1745 },
  { iataCode: 'LGA', name: 'LaGuardia Airport', city: 'New York', country: 'United States', latitude: 40.7769, longitude: -73.8740 },
  { iataCode: 'SEA', name: 'Seattle–Tacoma International Airport', city: 'Seattle', country: 'United States', latitude: 47.4502, longitude: -122.3088 },
  { iataCode: 'LHR', name: 'London Heathrow Airport', city: 'London', country: 'United Kingdom', latitude: 51.4700, longitude: -0.4543 },
  { iataCode: 'LGW', name: 'London Gatwick Airport', city: 'London', country: 'United Kingdom', latitude: 51.1537, longitude: -0.1821 },
  { iataCode: 'CDG', name: 'Paris Charles de Gaulle Airport', city: 'Paris', country: 'France', latitude: 49.0097, longitude: 2.5479 },
  { iataCode: 'ORY', name: 'Paris Orly Airport', city: 'Paris', country: 'France', latitude: 48.7262, longitude: 2.3652 },
  { iataCode: 'FRA', name: 'Frankfurt Airport', city: 'Frankfurt', country: 'Germany', latitude: 50.0379, longitude: 8.5622 },
  { iataCode: 'AMS', name: 'Amsterdam Airport Schiphol', city: 'Amsterdam', country: 'Netherlands', latitude: 52.3105, longitude: 4.7683 },
  { iataCode: 'SYD', name: 'Sydney Kingsford Smith Airport', city: 'Sydney', country: 'Australia', latitude: -33.9399, longitude: 151.1753 },
  { iataCode: 'MEL', name: 'Melbourne Airport', city: 'Melbourne', country: 'Australia', latitude: -37.6690, longitude: 144.8410 },
];

/** City aliases so a destination written in Chinese still finds its airports. */
const CITY_ALIASES: Record<string, string> = {
  釜山: 'Busan',
  首爾: 'Seoul',
  漢城: 'Seoul',
  濟州: 'Jeju',
  台北: 'Taipei',
  臺北: 'Taipei',
  高雄: 'Kaohsiung',
  東京: 'Tokyo',
  大阪: 'Osaka',
  札幌: 'Sapporo',
  福岡: 'Fukuoka',
  香港: 'Hong Kong',
  新加坡: 'Singapore',
  曼谷: 'Bangkok',
  上海: 'Shanghai',
  北京: 'Beijing',
  多倫多: 'Toronto',
  溫哥華: 'Vancouver',
  蒙特婁: 'Montreal',
  倫敦: 'London',
  巴黎: 'Paris',
  紐約: 'New York',
  洛杉磯: 'Los Angeles',
  舊金山: 'San Francisco',
  西雅圖: 'Seattle',
  雪梨: 'Sydney',
};

const normalize = (value: string) => value.trim().toLowerCase();

/** Resolve a free-text city (English or Chinese) to its directory city name. */
export const resolveCityName = (value: string): string | undefined => {
  const raw = value.trim();
  if (!raw) return undefined;
  const alias = Object.keys(CITY_ALIASES).find(key => raw.includes(key));
  if (alias) return CITY_ALIASES[alias];
  const match = AIRPORT_DIRECTORY.find(airport => normalize(airport.city) === normalize(raw));
  return match?.city;
};

/** Exact IATA lookup. Returns undefined for unknown codes rather than guessing. */
export const findAirportByIata = (code: string): FlightAirport | undefined => {
  const wanted = code.trim().toUpperCase();
  return AIRPORT_DIRECTORY.find(airport => airport.iataCode === wanted);
};

/**
 * Search the directory by IATA code, airport name or city.
 * Exact IATA matches rank first, then city matches, then name matches.
 */
export const searchAirports = (query: string, limit = 6): FlightAirport[] => {
  const raw = query.trim();
  if (!raw) return [];
  const term = normalize(raw);
  const cityTerm = resolveCityName(raw);
  const scored = AIRPORT_DIRECTORY.map(airport => {
    if (airport.iataCode.toLowerCase() === term) return { airport, score: 0 };
    if (cityTerm && airport.city === cityTerm) return { airport, score: 1 };
    if (normalize(airport.city).startsWith(term)) return { airport, score: 2 };
    if (normalize(airport.name).startsWith(term)) return { airport, score: 3 };
    if (normalize(airport.city).includes(term)) return { airport, score: 4 };
    if (normalize(airport.name).includes(term)) return { airport, score: 5 };
    return { airport, score: Number.POSITIVE_INFINITY };
  }).filter(entry => Number.isFinite(entry.score));
  scored.sort((a, b) => a.score - b.score || a.airport.iataCode.localeCompare(b.airport.iataCode));
  return scored.slice(0, limit).map(entry => entry.airport);
};

/**
 * Candidate airports for a trip destination.
 *
 * `primary` is set only when the city has exactly one reasonable airport —
 * a city with several (Taipei, Tokyo, London) must be chosen by the user.
 */
export const airportCandidatesForCity = (value: string): { candidates: FlightAirport[]; primary?: FlightAirport } => {
  const city = resolveCityName(value);
  if (!city) return { candidates: [] };
  const candidates = AIRPORT_DIRECTORY.filter(airport => airport.city === city);
  return { candidates, primary: candidates.length === 1 ? candidates[0] : undefined };
};

export const formatAirportLabel = (airport: FlightAirport): string =>
  `${airport.iataCode} · ${airport.name}`;
