import React, { useState } from 'react';
import { CommunityPost } from '../types';
import MyPostsPanel from './MyPostsPanel';
import { AuthProfile } from '../services/authService';
import { AuthStatus } from '../types';

interface Props { authStatus: AuthStatus; profile: AuthProfile | null; email?: string; authAvailable: boolean; onSignIn: () => void; onSignOut: () => void; onSaveProfile: (values: { displayName: string; avatarUrl?: string; bio?: string }) => Promise<void>; myPosts: CommunityPost[]; onTogglePostVisibility: (postId: string) => void; onDeletePost: (post: CommunityPost) => void; }
const AccountScreen: React.FC<Props> = ({ authStatus, profile, email, authAvailable, onSignIn, onSignOut, onSaveProfile, myPosts, onTogglePostVisibility, onDeletePost }) => { const [editing, setEditing] = useState(false); const [name, setName] = useState(profile?.displayName || ''); const [avatar, setAvatar] = useState(profile?.avatarUrl || ''); const [bio, setBio] = useState(profile?.bio || ''); const save = async (e: React.FormEvent) => { e.preventDefault(); await onSaveProfile({ displayName: name, avatarUrl: avatar, bio }); setEditing(false); }; return <main className="min-h-screen bg-[#f7f8fc] px-4 pb-28 pt-6 text-[#11183d] md:mx-auto md:max-w-2xl"><h1 className="text-2xl font-black">我的</h1>{authStatus === 'authenticated' && profile ? <div className="mt-6 space-y-4"><section className="rounded-[28px] bg-white p-6 shadow-sm"><div className="flex items-center gap-4"><div className="flex h-16 w-16 items-center justify-center overflow-hidden rounded-full bg-violet-100 text-2xl font-black text-violet-700">{profile.avatarUrl ? <img src={profile.avatarUrl} alt="" className="h-full w-full object-cover" /> : profile.displayName.slice(0, 1)}</div><div><h2 className="text-xl font-black">{profile.displayName}</h2><p className="mt-1 text-sm text-slate-500">{email || '已登入'}</p></div></div></section>{editing ? <form onSubmit={save} className="rounded-[28px] bg-white p-6 shadow-sm space-y-4"><label className="block text-sm font-bold">顯示名稱<input value={name} onChange={e => setName(e.target.value)} required className="mt-2 w-full rounded-2xl border border-slate-200 px-4 py-3" /></label><label className="block text-sm font-bold">Avatar URL<input value={avatar} onChange={e => setAvatar(e.target.value)} className="mt-2 w-full rounded-2xl border border-slate-200 px-4 py-3" /></label><label className="block text-sm font-bold">簡介<textarea value={bio} onChange={e => setBio(e.target.value)} rows={3} className="mt-2 w-full rounded-2xl border border-slate-200 px-4 py-3" /></label><button className="w-full rounded-2xl bg-violet-600 py-3 font-black text-white">儲存</button></form> : <div className="grid gap-3"><button onClick={() => setEditing(true)} className="rounded-2xl bg-white px-4 py-4 text-left font-black shadow-sm">編輯個人資料</button><button onClick={onSignOut} className="rounded-2xl bg-white px-4 py-4 text-left font-black text-rose-600 shadow-sm">登出</button></div>}</div> : <section className="mt-6 rounded-[28px] bg-white p-6 shadow-sm"><h2 className="text-xl font-black">登入 Trippie</h2><p className="mt-3 text-sm leading-6 text-slate-500">登入後可以建立你的創作者身份，未來也能跨裝置同步旅行資料。</p>{!authAvailable && <p className="mt-4 rounded-2xl bg-amber-50 p-3 text-sm font-bold text-amber-700">目前無法連線帳號服務</p>}<button onClick={onSignIn} disabled={!authAvailable} className="mt-6 w-full rounded-2xl bg-violet-600 py-3 font-black text-white disabled:opacity-50">登入 / 建立帳號</button></section>}
  {/* Inside the page, not after it: AccountScreen is min-h-screen, so anything
      rendered as its sibling sits a whole blank screen below the fold — which
      is exactly where this panel was and why nobody could find it. */}
  <div className="-mx-4 mt-6"><MyPostsPanel posts={myPosts} onToggleVisibility={onTogglePostVisibility} onDelete={onDeletePost} /></div>
  </main>; };
export default AccountScreen;
