import React, { useState } from 'react';
import { ExperienceNote, PostSlice } from '../types';

interface Props { candidates: PostSlice[]; onConfirm: (slices: PostSlice[]) => void | Promise<void>; onCancel: () => void; }
const PostSliceConfirmation: React.FC<Props> = ({ candidates, onConfirm, onCancel }) => {
  const [selected, setSelected] = useState(() => candidates.map(() => true));
  const [edited, setEdited] = useState(candidates);
  const [noteSelected, setNoteSelected] = useState<boolean[][]>(() => candidates.map(slice => slice.notes.map(() => true)));
  const update = (index: number, field: 'title' | 'summary', value: string) => setEdited(items => items.map((item, itemIndex) => itemIndex === index ? { ...item, [field]: value } : item));
  const updateNote = (sliceIndex: number, noteIndex: number, field: 'text' | 'type', value: string) => setEdited(items => items.map((item, itemIndex) => itemIndex === sliceIndex ? { ...item, notes: item.notes.map((note, currentIndex) => currentIndex === noteIndex ? { ...note, [field]: value } : note) } : item));
  return <section className="mt-6 rounded-3xl bg-violet-50 p-4">
    <h2 className="text-lg font-black text-[#11183d]">AI 找到 {candidates.length} 個旅行靈感</h2>
    <div className="mt-3 space-y-3">{edited.map((slice, index) => <div key={slice.id} className="rounded-2xl bg-white p-3"><label className="flex gap-3"><input type="checkbox" checked={selected[index]} onChange={() => setSelected(items => items.map((value, itemIndex) => itemIndex === index ? !value : value))} className="mt-1 h-4 w-4 accent-violet-600" /><div className="min-w-0 flex-1"><input value={slice.title} onChange={event => update(index, 'title', event.target.value)} className="w-full border-b border-slate-100 bg-transparent text-sm font-black outline-none" /><div className="mt-1 text-xs font-bold text-violet-600">{slice.type}</div>{slice.summary !== undefined && <textarea value={slice.summary || ''} onChange={event => update(index, 'summary', event.target.value)} rows={2} className="mt-2 w-full resize-none bg-transparent text-xs leading-5 text-slate-500 outline-none" />}</div></label><div className="mt-3 space-y-2 pl-7">{slice.notes.map((note, noteIndex) => <label key={`${slice.id}-note-${noteIndex}`} className="flex gap-2 rounded-xl bg-violet-50 p-2"><input type="checkbox" checked={noteSelected[index]?.[noteIndex] ?? true} onChange={() => setNoteSelected(items => items.map((values, sliceIdx) => sliceIdx === index ? values.map((value, currentIdx) => currentIdx === noteIndex ? !value : value) : values))} className="mt-1 h-4 w-4 accent-violet-600" /><div className="min-w-0 flex-1"><select value={note.type} onChange={event => updateNote(index, noteIndex, 'type', event.target.value)} className="mb-1 bg-transparent text-[11px] font-black text-violet-700 outline-none"><option value={note.type}>{note.type}</option><option value="recommendation">recommendation</option><option value="warning">warning</option><option value="timing">timing</option><option value="queue">queue</option><option value="packing">packing</option><option value="facility">facility</option><option value="practical">practical</option></select><textarea value={note.text} onChange={event => updateNote(index, noteIndex, 'text', event.target.value)} rows={2} className="w-full resize-none bg-transparent text-xs leading-5 text-slate-600 outline-none" /></div></label>)}</div></div>)}</div>
    <div className="mt-4 flex gap-2"><button type="button" onClick={onCancel} className="flex-1 rounded-2xl bg-white px-3 py-3 text-sm font-black text-slate-500">取消</button><button type="button" onClick={() => onConfirm(edited.flatMap((slice, index) => selected[index] ? [{ ...slice, notes: slice.notes.filter((_, noteIndex) => noteSelected[index]?.[noteIndex] !== false) }] : []))} className="flex-1 rounded-2xl bg-violet-600 px-3 py-3 text-sm font-black text-white">確認儲存</button></div>
  </section>;
};
export default PostSliceConfirmation;
