import React, { useEffect, useMemo, useRef, useState } from 'react';
import { OVERLAY } from '../constants/layers';
import { Check, ChevronDown, Globe2, Plus, Search, X } from 'lucide-react';
import { PassportProfile, TravelRules } from '../types';
import { isTravelRulesCurrent } from '../services/travelRulesCurrentness';

interface Props { tripId?: string | null; passports: PassportProfile[]; defaultPassportId?: string; selectedPassportId?: string; destination?: string; destinationCountry?: string; startDate?: string; endDate?: string; travelRules?: TravelRules; onResearchTravelRules?: (selectedId?: string) => Promise<TravelRules>; onSave: (passports: PassportProfile[], defaultId?: string, selectedId?: string) => void; onEditDestination?: () => void; onClose: () => void; }
type PassportOption = { countryCode: string; displayName: string; passportLabel: string; flag: string; aliases: string[] };
const OPTIONS: PassportOption[] = [
  ['TW','台灣','台灣護照','🇹🇼',['台灣','台湾','Taiwan','TW','中華民國','Republic of China','ROC']], ['JP','日本','日本護照','🇯🇵',['日本','Japan','JP']], ['KR','韓國','韓國護照','🇰🇷',['韓國','韩国','South Korea','Korea','KR']], ['HK','香港','香港特別行政區護照','🇭🇰',['香港','Hong Kong','HK']], ['MO','澳門','澳門特別行政區護照','🇲🇴',['澳門','澳门','Macau','Macao','MO']], ['CN','中國','中華人民共和國護照','🇨🇳',['中國','中国','China','CN']], ['SG','新加坡','新加坡護照','🇸🇬',['新加坡','Singapore','SG']], ['MY','馬來西亞','馬來西亞護照','🇲🇾',['馬來西亞','Malaysia','MY']], ['TH','泰國','泰國護照','🇹🇭',['泰國','Thailand','TH']], ['VN','越南','越南護照','🇻🇳',['越南','Vietnam','VN']], ['PH','菲律賓','菲律賓護照','🇵🇭',['菲律賓','菲律宾','Philippines','PH']], ['ID','印尼','印尼護照','🇮🇩',['印尼','Indonesia','ID']], ['CA','加拿大','加拿大護照','🇨🇦',['加拿大','Canada','CA']], ['US','美國','美國護照','🇺🇸',['美國','美国','United States','USA','US']], ['GB','英國','英國護照','🇬🇧',['英國','英国','United Kingdom','UK','GB']], ['FR','法國','法國護照','🇫🇷',['法國','法国','France','FR']], ['DE','德國','德國護照','🇩🇪',['德國','德国','Germany','DE']], ['IT','義大利','義大利護照','🇮🇹',['義大利','意大利','Italy','IT']], ['ES','西班牙','西班牙護照','🇪🇸',['西班牙','Spain','ES']], ['AU','澳洲','澳洲護照','🇦🇺',['澳洲','澳大利亞','Australia','AU']], ['NZ','紐西蘭','紐西蘭護照','🇳🇿',['紐西蘭','新西兰','New Zealand','NZ']]
].map(([countryCode, displayName, passportLabel, flag, aliases]) => ({ countryCode, displayName, passportLabel, flag, aliases } as PassportOption));
const optionFor = (passport?: PassportProfile) => OPTIONS.find(option => option.countryCode === passport?.countryCode) || OPTIONS.find(option => option.displayName === passport?.country);
const labelFor = (passport: PassportProfile) => optionFor(passport)?.passportLabel || `${passport.country}護照`;

const TravelIdentityModal: React.FC<Props> = ({ tripId, passports: initial, defaultPassportId, selectedPassportId, destination, destinationCountry, startDate, endDate, travelRules, onResearchTravelRules, onSave, onEditDestination, onClose }) => {
  const [passports, setPassports] = useState(initial); const [selected, setSelected] = useState(selectedPassportId || defaultPassportId || ''); const [defaultId, setDefaultId] = useState(defaultPassportId || ''); const [open, setOpen] = useState(initial.length === 0); const [query, setQuery] = useState(''); const [researchError, setResearchError] = useState<string | null>(null); const inputRef = useRef<HTMLInputElement>(null); const requestInFlight = useRef(false);
  const selectedPassport = passports.find(passport => passport.id === selected); const selectedOption = optionFor(selectedPassport);
  const currentDestination = (destination || destinationCountry || '').trim();
  const currentTrip = { id: tripId, destination: currentDestination, startDate, endDate, travelRules };
  const currentContextKey = [tripId || '', currentDestination, selectedPassport?.countryCode || '', startDate || '', endDate || ''].join('|');
  const [requestState, setRequestState] = useState<'NEEDS_UPDATE' | 'UPDATING' | 'UPDATED'>(() => isTravelRulesCurrent(currentTrip, selectedPassport) ? 'UPDATED' : 'NEEDS_UPDATE');
  const previousContextKey = useRef(currentContextKey);
  useEffect(() => { if (previousContextKey.current !== currentContextKey) { previousContextKey.current = currentContextKey; setRequestState('NEEDS_UPDATE'); setResearchError(null); } }, [currentContextKey]);
  const handleSaveAndResearch = async () => { if (!passports.length || !selected || requestState === 'UPDATING' || requestInFlight.current) return; setResearchError(null); onSave(passports, defaultId || undefined, selected); if (!onResearchTravelRules) { setRequestState('UPDATED'); return; } requestInFlight.current = true; setRequestState('UPDATING'); try { await onResearchTravelRules(selected); setRequestState('UPDATED'); } catch { setResearchError('旅行規定暫時無法更新，稍後可再試。'); setRequestState('NEEDS_UPDATE'); } finally { requestInFlight.current = false; } };
  const matches = useMemo(() => { const q = query.trim().toLocaleLowerCase(); return OPTIONS.filter(option => !q || [option.displayName, option.passportLabel, option.countryCode, ...option.aliases].join(' ').toLocaleLowerCase().includes(q)); }, [query]);
  const focusSearch = () => setTimeout(() => inputRef.current?.focus(), 0);
  const choose = (option: PassportOption) => { const existing = passports.find(passport => passport.countryCode === option.countryCode); if (existing) { setSelected(existing.id); } else { const next = { id: `passport_${Date.now().toString(36)}`, country: option.displayName, countryCode: option.countryCode }; setPassports(current => [...current, next]); setSelected(next.id); if (!defaultId) setDefaultId(next.id); } setQuery(''); setOpen(false); };
  return <div className={`fixed inset-0 ${OVERLAY.modal} flex items-center justify-center bg-[#111a4a]/40 p-4 backdrop-blur-sm`}><div className="max-h-[calc(100dvh-32px)] w-full max-w-[430px] overflow-y-auto rounded-[28px] bg-white p-5 shadow-[0_24px_70px_rgba(17,26,74,.22)] sm:p-6">
    <header className="flex items-start justify-between"><div><div className="flex items-center gap-2 text-[#5b3df5]"><Globe2 size={21}/><span className="text-[10px] font-extrabold uppercase tracking-[.16em]">TRAVEL IDENTITY</span></div><h2 className="mt-2 text-[22px] font-black tracking-tight text-[#111A4A]">旅行身分與入境資訊</h2><p className="mt-2 max-w-[315px] text-[13px] leading-5 text-slate-500">我們會依本次目的地與你使用的護照，查詢相關旅行規定。</p></div><button type="button" onClick={onClose} aria-label="關閉" className="rounded-full bg-[#f2efff] p-2.5 text-[#5b3df5]"><X size={18}/></button></header>
    <section className="mt-6"><p className="mb-2 text-xs font-bold text-slate-500">本次目的地</p><div className="flex items-center justify-between rounded-2xl border border-[#e5e3f1] bg-[#faf9ff] px-4 py-3.5"><div><p className="text-base font-extrabold text-[#111A4A]">{destination || '尚未設定目的地'}</p>{destinationCountry && <p className="mt-0.5 text-xs text-slate-500">{destinationCountry}</p>}</div>{onEditDestination ? <button type="button" onClick={onEditDestination} className="rounded-xl bg-white px-3 py-2 text-xs font-bold text-[#5b3df5] shadow-sm">{destination ? '更改' : '設定目的地'}</button> : <span className="text-[11px] font-bold text-slate-400">{destination ? '來自本次旅程' : '請於旅程設定填寫'}</span>}</div></section>
    <section className="mt-6"><div className="mb-3 flex items-center justify-between"><h3 className="text-sm font-black text-[#111A4A]">這趟旅程使用的護照 <span className="text-[#e54870]">*</span></h3><button type="button" onClick={() => { setOpen(true); focusSearch(); }} className="flex min-h-11 items-center gap-1 rounded-xl px-2 text-xs font-bold text-[#5b3df5]"><Plus size={15}/>新增護照</button></div>
      {selectedPassport && !open ? <button type="button" onClick={() => { setOpen(true); focusSearch(); }} className="flex min-h-14 w-full items-center justify-between rounded-2xl border border-[#cfc7ff] bg-[#faf9ff] p-3.5 text-left"><span className="flex items-center gap-3"><span className="text-2xl">{selectedOption?.flag || '🌐'}</span><span><span className="block text-sm font-extrabold text-[#111A4A]">{selectedOption?.passportLabel || labelFor(selectedPassport)}</span><span className="mt-0.5 block text-xs text-slate-500">{defaultId === selectedPassport.id ? '預設' : '這趟旅程使用'}</span></span></span><span className="flex items-center gap-1 text-xs font-bold text-[#5b3df5]">更換 <ChevronDown size={16}/></span></button> : <div className="relative"><div className="flex min-h-12 items-center gap-2 rounded-2xl border border-[#cfc7ff] bg-white px-3"><Search size={18} className="text-slate-400"/><input ref={inputRef} autoFocus={open} value={query} onFocus={() => setOpen(true)} onChange={event => { setQuery(event.target.value); setOpen(true); }} onKeyDown={event => { if (event.key === 'Escape') setOpen(false); if (event.key === 'Enter' && matches[0]) { event.preventDefault(); choose(matches[0]); } }} placeholder={selectedOption ? `${selectedOption.flag} ${selectedOption.passportLabel}` : '搜尋護照國籍（例如 Taiwan、TW）'} className="min-w-0 flex-1 bg-transparent text-sm font-semibold text-[#111A4A] outline-none" aria-label="搜尋護照國籍"/>{query && <button type="button" onClick={() => setQuery('')} aria-label="清除搜尋" className="rounded-full p-2 text-slate-400"><X size={16}/></button>}<ChevronDown size={17} className="text-slate-400"/></div>{open && <div className="absolute z-10 mt-2 max-h-64 w-full overflow-y-auto rounded-2xl border border-[#e5e3f1] bg-white p-2 shadow-[0_12px_28px_rgba(17,26,74,.16)]">{matches.length ? matches.map(option => <button key={option.countryCode} type="button" onClick={() => choose(option)} className={`flex min-h-12 w-full items-center gap-3 rounded-xl px-3 text-left ${option.countryCode === selectedOption?.countryCode ? 'bg-[#f0edff]' : 'hover:bg-[#faf9ff]'}`}><span className="text-xl">{option.flag}</span><span className="min-w-0 flex-1"><span className="block text-sm font-bold text-[#111A4A]">{option.passportLabel}</span><span className="block text-xs text-slate-500">{option.displayName} · {option.countryCode}</span></span>{option.countryCode === selectedOption?.countryCode && <Check size={17} className="text-[#5b3df5]"/>}</button>) : <p className="p-4 text-center text-xs text-slate-400">找不到符合的護照國籍</p>}</div>}</div>}
      {open && passports.length > 0 && <div className="mt-2 max-h-52 space-y-2 overflow-y-auto">{passports.map(passport => <div key={passport.id} className="flex items-center justify-between rounded-2xl border border-[#e8e7f1] bg-white p-3"><button type="button" onClick={() => { setSelected(passport.id); setOpen(false); }} className="flex min-h-11 items-center gap-3 text-left"><span className="text-xl">{optionFor(passport)?.flag || '🌐'}</span><span><span className="block text-sm font-bold text-[#111A4A]">{optionFor(passport)?.passportLabel || labelFor(passport)}</span><span className="block text-xs text-slate-500">{optionFor(passport)?.displayName || passport.country} · {passport.countryCode || '—'}</span></span></button><button type="button" onClick={() => setDefaultId(passport.id)} className={`rounded-full px-2.5 py-1.5 text-[10px] font-bold ${defaultId === passport.id ? 'bg-[#5b3df5] text-white' : 'bg-[#f4f3f8] text-slate-500'}`}>{defaultId === passport.id ? '預設' : '設為預設'}</button></div>)}</div>}
    </section><div className="mt-5 flex items-start gap-3 rounded-2xl bg-[#f3f0ff] p-3.5"><span className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-md bg-[#5b3df5] text-white"><Check size={14}/></span><div><p className="text-xs font-bold text-[#111A4A]">儲存於我的旅行資料</p><p className="mt-1 text-[11px] leading-4 text-slate-500">下次建立旅程時會自動帶入，可隨時更換。</p></div></div><button type="button" onClick={handleSaveAndResearch} disabled={!passports.length || !selected || requestState === 'UPDATING' || requestState === 'UPDATED'} className="mt-5 min-h-12 w-full rounded-2xl bg-gradient-to-r from-[#2F5BFF] to-[#8B3DFF] text-sm font-black text-white shadow-[0_10px_22px_rgba(91,61,245,.24)]">{requestState === 'UPDATING' ? '正在更新旅行規定…' : requestState === 'UPDATED' ? '✓ 旅行規定已更新' : '儲存並更新旅行規定'}</button>
    {requestState === 'UPDATED' && <div className="mt-4 rounded-2xl bg-[#f3f0ff] p-3.5 text-xs leading-5 text-[#4d35c7]"><p className="font-black">✓ 旅行規定已更新</p><p>入境規定已同步至旅行前準備</p><p>退稅規定已準備供記帳使用</p><button type="button" onClick={handleSaveAndResearch} disabled={requestState === 'UPDATING'} className="mt-2 font-bold underline underline-offset-2">重新整理旅行規定</button></div>}
    {researchError && requestState !== 'UPDATED' && <div className="mt-4 rounded-2xl bg-[#fff7f8] p-3.5 text-xs leading-5 text-rose-600">旅行規定暫時無法更新，稍後可再試。</div>}
  </div></div>;
}; export default TravelIdentityModal;
